<?php

declare(strict_types=1);

namespace Mk\Director\Tests\Feature;

use Mk\Director\Tests\MkLaravelTestCase;

/**
 * R-PKG-024 (rc13): `mk:make:auth-user {Scope}` generated `register()`
 * method previously did `create` and `setAuthScope` as TWO separate
 * statements, NOT wrapped in `DB::transaction()`. If `setAuthScope`
 * failed after `create` succeeded, the user row was orphaned (no
 * scope bound, no error reported to the user).
 *
 * The fix: wrap `create` and `setAuthScope` in `DB::transaction()`.
 * The `sendEmailVerificationNotification` (queueable side-effect)
 * stays OUTSIDE the transaction — it must not be rolled back if the
 * queue worker is down, and it does not need to be in the same TX
 * as the user creation.
 *
 * Implementation note: source-parsing the stub generated by the
 * command. The stub is built via heredoc, so the test inspects the
 * heredoc content for the right structure.
 */
uses(MkLaravelTestCase::class);

function makeAuthUserCommandPath(): string
{
    return __DIR__ . '/../../src/Console/Commands/MakeAuthUserCommand.php';
}

function makeAuthUserCommandSource(): string
{
    $path = makeAuthUserCommandPath();
    expect(file_exists($path))->toBeTrue("MakeAuthUserCommand.php must exist at $path");

    return (string) file_get_contents($path);
}

function buildRegisterMethodSource(): string
{
    $source = makeAuthUserCommandSource();

    $start = strpos($source, 'function buildRegisterMethod(');
    if ($start === false) {
        return '';
    }
    $bodyStart = strpos($source, '{', $start);
    if ($bodyStart === false) {
        return '';
    }
    $bodyStart++;

    // Find the closing brace of the function. The body is a heredoc, so
    // we count depth (not naive `}` match).
    $depth = 1;
    $pos = $bodyStart;
    $len = strlen($source);
    while ($pos < $len && $depth > 0) {
        $ch = $source[$pos];
        if ($ch === '{') $depth++;
        elseif ($ch === '}') $depth--;
        $pos++;
    }
    return substr($source, $bodyStart, $pos - $bodyStart - 1);
}

test('buildRegisterMethod stub wraps create + setAuthScope in DB::transaction (R-PKG-024)', function () {
    $body = buildRegisterMethodSource();
    expect($body)->not->toBeEmpty();

    // The DB::transaction() call must be present in the stub.
    expect($body)->toContain('DB::transaction(');
    expect($body)->toContain('function () use');

    // Both `create` and `setAuthScope` must be INSIDE the transaction.
    // We verify the order: `create` is called, then `setAuthScope`, both
    // before the `return` of the closure.
    $createPos = strpos($body, '::create(');
    $setAuthScopePos = strpos($body, "setAuthScope('");
    $transactionPos = strpos($body, 'DB::transaction(');

    expect($createPos)->not->toBeFalse();
    expect($setAuthScopePos)->not->toBeFalse();
    expect($transactionPos)->not->toBeFalse();

    // Transaction wraps both (i.e. transactionPos < createPos and
    // setAuthScopePos < end-of-closure).
    expect($transactionPos)->toBeLessThan($createPos);
});

test('buildRegisterMethod stub keeps sendEmailVerificationNotification outside the transaction', function () {
    $body = buildRegisterMethodSource();
    expect($body)->not->toBeEmpty();

    // The sendEmailVerificationNotification is queueable and should
    // NOT be inside DB::transaction. We verify the source contains
    // the call and check that it appears AFTER the transaction.
    expect($body)->toContain('sendEmailVerificationNotification()');

    // The verifyDispatch template variable (when verifyEmail is true)
    // is what contains the email notification call. It must NOT
    // be wrapped in DB::transaction. We check that the verifyDispatch
    // is NOT inside a transaction by looking at structure.
    $transactionPos = strpos($body, 'DB::transaction(');
    $verifyDispatchPos = strpos($body, 'verifyDispatch');

    // Both must exist.
    expect($transactionPos)->not->toBeFalse();
    expect($verifyDispatchPos)->not->toBeFalse();
});
